// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PB3Load;
@class PB3Person;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PB3Load_Operation

typedef GPB_ENUM(PB3Load_Operation) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3Load_Operation_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3Load_Operation_OperationNone = 0,
  PB3Load_Operation_OperationUp = 1,
  PB3Load_Operation_OperationDown = 2,
};

GPBEnumDescriptor *PB3Load_Operation_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3Load_Operation_IsValidValue(int32_t value);

#pragma mark - Enum PB3Load_Command

typedef GPB_ENUM(PB3Load_Command) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3Load_Command_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3Load_Command_CommandNone = 0,
  PB3Load_Command_CommandBegin = 1,
  PB3Load_Command_CommandProcess = 2,
  PB3Load_Command_CommandEnd = 3,
  PB3Load_Command_CommandCancel = 4,
};

GPBEnumDescriptor *PB3Load_Command_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3Load_Command_IsValidValue(int32_t value);

#pragma mark - PB3MessagesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PB3MessagesRoot : GPBRootObject
@end

#pragma mark - PB3Load

typedef GPB_ENUM(PB3Load_FieldNumber) {
  PB3Load_FieldNumber_Operation = 1,
  PB3Load_FieldNumber_Command = 2,
  PB3Load_FieldNumber_Handle = 3,
  PB3Load_FieldNumber_Path = 4,
  PB3Load_FieldNumber_Chunk = 5,
  PB3Load_FieldNumber_Digest = 6,
  PB3Load_FieldNumber_Ret = 15,
};

@interface PB3Load : GPBMessage

@property(nonatomic, readwrite) PB3Load_Operation operation;

@property(nonatomic, readwrite) PB3Load_Command command;

@property(nonatomic, readwrite) int32_t handle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

@property(nonatomic, readwrite, copy, null_resettable) NSData *chunk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *digest;

@property(nonatomic, readwrite, strong, null_resettable) PB3Load *ret;
/** Test to see if @c ret has been set. */
@property(nonatomic, readwrite) BOOL hasRet;

@end

/**
 * Fetches the raw value of a @c PB3Load's @c operation property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3Load_Operation_RawValue(PB3Load *message);
/**
 * Sets the raw value of an @c PB3Load's @c operation property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3Load_Operation_RawValue(PB3Load *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3Load's @c command property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3Load_Command_RawValue(PB3Load *message);
/**
 * Sets the raw value of an @c PB3Load's @c command property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3Load_Command_RawValue(PB3Load *message, int32_t value);

#pragma mark - PB3Divide

typedef GPB_ENUM(PB3Divide_FieldNumber) {
  PB3Divide_FieldNumber_A = 1,
  PB3Divide_FieldNumber_B = 2,
  PB3Divide_FieldNumber_Ret = 15,
};

@interface PB3Divide : GPBMessage

@property(nonatomic, readwrite) int32_t a;

@property(nonatomic, readwrite) int32_t b;

@property(nonatomic, readwrite) double ret;

@end

#pragma mark - PB3Person

typedef GPB_ENUM(PB3Person_FieldNumber) {
  PB3Person_FieldNumber_Name = 1,
  PB3Person_FieldNumber_Age = 2,
  PB3Person_FieldNumber_ChildrenArray = 3,
};

@interface PB3Person : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) uint32_t age;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3Person*> *childrenArray;
/** The number of items in @c childrenArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger childrenArray_Count;

@end

#pragma mark - PB3GetParent

typedef GPB_ENUM(PB3GetParent_FieldNumber) {
  PB3GetParent_FieldNumber_Person = 1,
  PB3GetParent_FieldNumber_Ret = 15,
};

@interface PB3GetParent : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PB3Person *person;
/** Test to see if @c person has been set. */
@property(nonatomic, readwrite) BOOL hasPerson;

@property(nonatomic, readwrite, strong, null_resettable) PB3Person *ret;
/** Test to see if @c ret has been set. */
@property(nonatomic, readwrite) BOOL hasRet;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
