// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBELoad;
@class GPBEPerson;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GPBELoad_Operation

typedef GPB_ENUM(GPBELoad_Operation) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GPBELoad_Operation_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  GPBELoad_Operation_OperationNone = 0,
  GPBELoad_Operation_OperationUp = 1,
  GPBELoad_Operation_OperationDown = 2,
};

GPBEnumDescriptor *GPBELoad_Operation_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GPBELoad_Operation_IsValidValue(int32_t value);

#pragma mark - Enum GPBELoad_Command

typedef GPB_ENUM(GPBELoad_Command) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GPBELoad_Command_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  GPBELoad_Command_CommandNone = 0,
  GPBELoad_Command_CommandBegin = 1,
  GPBELoad_Command_CommandProcess = 2,
  GPBELoad_Command_CommandEnd = 3,
  GPBELoad_Command_CommandCancel = 4,
};

GPBEnumDescriptor *GPBELoad_Command_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GPBELoad_Command_IsValidValue(int32_t value);

#pragma mark - GPBEMessagesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GPBEMessagesRoot : GPBRootObject
@end

#pragma mark - GPBELoad

typedef GPB_ENUM(GPBELoad_FieldNumber) {
  GPBELoad_FieldNumber_Operation = 1,
  GPBELoad_FieldNumber_Command = 2,
  GPBELoad_FieldNumber_Handle = 3,
  GPBELoad_FieldNumber_Path = 4,
  GPBELoad_FieldNumber_Chunk = 5,
  GPBELoad_FieldNumber_Digest = 6,
  GPBELoad_FieldNumber_Ret = 15,
};

@interface GPBELoad : GPBMessage

@property(nonatomic, readwrite) GPBELoad_Operation operation;

@property(nonatomic, readwrite) GPBELoad_Command command;

@property(nonatomic, readwrite) int32_t handle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

@property(nonatomic, readwrite, copy, null_resettable) NSData *chunk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *digest;

@property(nonatomic, readwrite, strong, null_resettable) GPBELoad *ret;
/** Test to see if @c ret has been set. */
@property(nonatomic, readwrite) BOOL hasRet;

@end

/**
 * Fetches the raw value of a @c GPBELoad's @c operation property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GPBELoad_Operation_RawValue(GPBELoad *message);
/**
 * Sets the raw value of an @c GPBELoad's @c operation property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGPBELoad_Operation_RawValue(GPBELoad *message, int32_t value);

/**
 * Fetches the raw value of a @c GPBELoad's @c command property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GPBELoad_Command_RawValue(GPBELoad *message);
/**
 * Sets the raw value of an @c GPBELoad's @c command property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGPBELoad_Command_RawValue(GPBELoad *message, int32_t value);

#pragma mark - GPBEDivide

typedef GPB_ENUM(GPBEDivide_FieldNumber) {
  GPBEDivide_FieldNumber_A = 1,
  GPBEDivide_FieldNumber_B = 2,
  GPBEDivide_FieldNumber_Ret = 15,
};

@interface GPBEDivide : GPBMessage

@property(nonatomic, readwrite) int32_t a;

@property(nonatomic, readwrite) int32_t b;

@property(nonatomic, readwrite) double ret;

@end

#pragma mark - GPBEPerson

typedef GPB_ENUM(GPBEPerson_FieldNumber) {
  GPBEPerson_FieldNumber_Name = 1,
  GPBEPerson_FieldNumber_Age = 2,
  GPBEPerson_FieldNumber_ChildrenArray = 3,
};

@interface GPBEPerson : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) uint32_t age;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBEPerson*> *childrenArray;
/** The number of items in @c childrenArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger childrenArray_Count;

@end

#pragma mark - GPBEGetParent

typedef GPB_ENUM(GPBEGetParent_FieldNumber) {
  GPBEGetParent_FieldNumber_Person = 1,
  GPBEGetParent_FieldNumber_Ret = 15,
};

@interface GPBEGetParent : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBEPerson *person;
/** Test to see if @c person has been set. */
@property(nonatomic, readwrite) BOOL hasPerson;

@property(nonatomic, readwrite, strong, null_resettable) GPBEPerson *ret;
/** Test to see if @c ret has been set. */
@property(nonatomic, readwrite) BOOL hasRet;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
