// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Messages.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PB3MessagesRoot

@implementation PB3MessagesRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - PB3MessagesRoot_FileDescriptor

static GPBFileDescriptor *PB3MessagesRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"PB3"
                                                 objcPrefix:@"PB3"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - PB3Load

@implementation PB3Load

@dynamic operation;
@dynamic command;
@dynamic handle;
@dynamic path;
@dynamic chunk;
@dynamic digest;
@dynamic hasRet, ret;

typedef struct PB3Load__storage_ {
  uint32_t _has_storage_[1];
  PB3Load_Operation operation;
  PB3Load_Command command;
  int32_t handle;
  NSString *path;
  NSData *chunk;
  NSData *digest;
  PB3Load *ret;
} PB3Load__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "operation",
        .dataTypeSpecific.enumDescFunc = PB3Load_Operation_EnumDescriptor,
        .number = PB3Load_FieldNumber_Operation,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PB3Load__storage_, operation),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "command",
        .dataTypeSpecific.enumDescFunc = PB3Load_Command_EnumDescriptor,
        .number = PB3Load_FieldNumber_Command,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PB3Load__storage_, command),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "handle",
        .dataTypeSpecific.className = NULL,
        .number = PB3Load_FieldNumber_Handle,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PB3Load__storage_, handle),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "path",
        .dataTypeSpecific.className = NULL,
        .number = PB3Load_FieldNumber_Path,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PB3Load__storage_, path),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "chunk",
        .dataTypeSpecific.className = NULL,
        .number = PB3Load_FieldNumber_Chunk,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PB3Load__storage_, chunk),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "digest",
        .dataTypeSpecific.className = NULL,
        .number = PB3Load_FieldNumber_Digest,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PB3Load__storage_, digest),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "ret",
        .dataTypeSpecific.className = GPBStringifySymbol(PB3Load),
        .number = PB3Load_FieldNumber_Ret,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PB3Load__storage_, ret),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PB3Load class]
                                     rootClass:[PB3MessagesRoot class]
                                          file:PB3MessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PB3Load__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t PB3Load_Operation_RawValue(PB3Load *message) {
  GPBDescriptor *descriptor = [PB3Load descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:PB3Load_FieldNumber_Operation];
  return GPBGetMessageInt32Field(message, field);
}

void SetPB3Load_Operation_RawValue(PB3Load *message, int32_t value) {
  GPBDescriptor *descriptor = [PB3Load descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:PB3Load_FieldNumber_Operation];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

int32_t PB3Load_Command_RawValue(PB3Load *message) {
  GPBDescriptor *descriptor = [PB3Load descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:PB3Load_FieldNumber_Command];
  return GPBGetMessageInt32Field(message, field);
}

void SetPB3Load_Command_RawValue(PB3Load *message, int32_t value) {
  GPBDescriptor *descriptor = [PB3Load descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:PB3Load_FieldNumber_Command];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum PB3Load_Operation

GPBEnumDescriptor *PB3Load_Operation_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "OperationNone\000OperationUp\000OperationDown\000";
    static const int32_t values[] = {
        PB3Load_Operation_OperationNone,
        PB3Load_Operation_OperationUp,
        PB3Load_Operation_OperationDown,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(PB3Load_Operation)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:PB3Load_Operation_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL PB3Load_Operation_IsValidValue(int32_t value__) {
  switch (value__) {
    case PB3Load_Operation_OperationNone:
    case PB3Load_Operation_OperationUp:
    case PB3Load_Operation_OperationDown:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Enum PB3Load_Command

GPBEnumDescriptor *PB3Load_Command_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "CommandNone\000CommandBegin\000CommandProcess\000"
        "CommandEnd\000CommandCancel\000";
    static const int32_t values[] = {
        PB3Load_Command_CommandNone,
        PB3Load_Command_CommandBegin,
        PB3Load_Command_CommandProcess,
        PB3Load_Command_CommandEnd,
        PB3Load_Command_CommandCancel,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(PB3Load_Command)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:PB3Load_Command_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL PB3Load_Command_IsValidValue(int32_t value__) {
  switch (value__) {
    case PB3Load_Command_CommandNone:
    case PB3Load_Command_CommandBegin:
    case PB3Load_Command_CommandProcess:
    case PB3Load_Command_CommandEnd:
    case PB3Load_Command_CommandCancel:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - PB3Divide

@implementation PB3Divide

@dynamic a;
@dynamic b;
@dynamic ret;

typedef struct PB3Divide__storage_ {
  uint32_t _has_storage_[1];
  int32_t a;
  int32_t b;
  double ret;
} PB3Divide__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "a",
        .dataTypeSpecific.className = NULL,
        .number = PB3Divide_FieldNumber_A,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PB3Divide__storage_, a),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "b",
        .dataTypeSpecific.className = NULL,
        .number = PB3Divide_FieldNumber_B,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PB3Divide__storage_, b),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "ret",
        .dataTypeSpecific.className = NULL,
        .number = PB3Divide_FieldNumber_Ret,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PB3Divide__storage_, ret),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PB3Divide class]
                                     rootClass:[PB3MessagesRoot class]
                                          file:PB3MessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PB3Divide__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PB3Person

@implementation PB3Person

@dynamic name;
@dynamic age;
@dynamic childrenArray, childrenArray_Count;

typedef struct PB3Person__storage_ {
  uint32_t _has_storage_[1];
  uint32_t age;
  NSString *name;
  NSMutableArray *childrenArray;
} PB3Person__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = PB3Person_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PB3Person__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "age",
        .dataTypeSpecific.className = NULL,
        .number = PB3Person_FieldNumber_Age,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PB3Person__storage_, age),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "childrenArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PB3Person),
        .number = PB3Person_FieldNumber_ChildrenArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PB3Person__storage_, childrenArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PB3Person class]
                                     rootClass:[PB3MessagesRoot class]
                                          file:PB3MessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PB3Person__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PB3GetParent

@implementation PB3GetParent

@dynamic hasPerson, person;
@dynamic hasRet, ret;

typedef struct PB3GetParent__storage_ {
  uint32_t _has_storage_[1];
  PB3Person *person;
  PB3Person *ret;
} PB3GetParent__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "person",
        .dataTypeSpecific.className = GPBStringifySymbol(PB3Person),
        .number = PB3GetParent_FieldNumber_Person,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PB3GetParent__storage_, person),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "ret",
        .dataTypeSpecific.className = GPBStringifySymbol(PB3Person),
        .number = PB3GetParent_FieldNumber_Ret,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PB3GetParent__storage_, ret),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PB3GetParent class]
                                     rootClass:[PB3MessagesRoot class]
                                          file:PB3MessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PB3GetParent__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
